### PR TITLE
Added ability to run shell command from menu

### PR DESCRIPTION
**Pull request by adamwojs**
Added ability to run shell command from menu via fake cmd:// protocol.

### CODE REVIEW

**Comment by corenominal** [comment]
Looks good and I like the fake protocol idea. I'm just a bit concerned that it errors when there is an existing settings file.

**Comment by adamwojs** [comment]
I will try fix this tomorrow.

**Comment by mouradhamoud** [comment]
Is it possible to pass command line args to this?

**Comment by adamwojs** [comment]
Yes, current implementation substitute %s with everything after cmd:// w.g `cmd://sudo service apache2 restart" ` will execute `gnome-terminal -e 'sudo service apache2 restart'`.

**Comment by mouradhamoud** [comment]
Nice, this is a feature I wanted but didn't have free time to add it.

As mentioned by @corenominal It should handle existing settings file gracefully.

**Comment by adamwojs** [comment]
Missing JSON keys shouldn't be problem now

**Comment by corenominal** [comment]
@adamwojs nice work and thank you for contributing. I love this feature and I'll rebuild the PPA package to include it.

**Pull request merged**
